# Generated by Django 5.2.4 on 2025-08-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePlatforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(upload_to='platform_icons/')),
                ('access_link', models.URLField(max_length=300)),
            ],
            options={
                'verbose_name': 'Available Platform',
                'verbose_name_plural': 'Available Platforms',
            },
        ),
    ]
