# Generated by Django 5.2.4 on 2025-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableplatforms',
            name='icon',
            field=models.URLField(max_length=300),
        ),
    ]
