# Generated by Django 5.2.4 on 2025-08-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_alter_availableplatforms_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableplatforms',
            name='access_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
