# Generated by Django 5.2.4 on 2025-08-04 12:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_userconnect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userconnect',
            unique_together={('user', 'platform')},
        ),
    ]
