# Generated by Django 5.2.3 on 2025-08-12 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_alter_userconnect_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_model_links', to='platforms.availableplatforms')),
            ],
            options={
                'verbose_name': 'Platform Model Availability',
                'verbose_name_plural': 'Platform Model Availabilities',
                'unique_together': {('platform', 'model')},
            },
        ),
    ]
