# Generated by Django 5.2.3 on 2025-08-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0006_platformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformmodel',
            name='support',
            field=models.BooleanField(default=True),
        ),
    ]
