# Generated by Django 5.2.3 on 2025-08-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0007_platformmodel_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnect',
            name='model_name',
            field=models.TextField(),
        ),
    ]
