# Generated by Django 5.2.4 on 2025-07-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Name of the AI model', max_length=100, unique=True)),
                ('input_price_per_token', models.DecimalField(decimal_places=8, help_text='Price per input token in USD', max_digits=10)),
                ('output_price_per_token', models.DecimalField(decimal_places=8, help_text='Price per output token in USD', max_digits=10)),
                ('provider', models.CharField(blank=True, help_text='Model provider (e.g., OpenAI, Anthropic)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the model is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['model_name'],
            },
        ),
    ]
