# Generated by Django 5.2.4 on 2025-07-29 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='backend_model_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Backend identifier for the model', max_length=100),
            preserve_default=False,
        ),
    ]
