# Generated by Django 5.1.4 on 2025-04-14 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='user prompt')),
                ('answer', models.TextField(help_text='The prompt answer')),
                ('html', models.TextField(help_text='The generated HTML code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='html_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HTML Generation',
                'verbose_name_plural': 'HTML Generations',
                'ordering': ['-created_at'],
            },
        ),
    ]
