services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: cd HindAI_Apis/HindAi_project && uvicorn HindAi_project.asgi:application --host 0.0.0.0 --port $PORT
