# Generated by Django 5.2.4 on 2025-07-29 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username for credit tracking', max_length=150, unique=True)),
                ('current_credits', models.DecimalField(decimal_places=2, default=0.0, help_text='Current available credits for the user', max_digits=10)),
                ('total_credits_purchased', models.DecimalField(decimal_places=2, default=0.0, help_text='Total credits ever purchased by user', max_digits=10)),
                ('total_credits_used', models.DecimalField(decimal_places=2, default=0.0, help_text='Total credits used by user', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credit',
                'verbose_name_plural': 'User Credits',
                'ordering': ['-updated_at'],
            },
        ),
    ]
