# Generated by Django 5.2.3 on 2025-09-03 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAttachedDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='Name of the trading platform (e.g., TD Ameritrade, E*TRADE)', max_length=1000)),
                ('account_id', models.CharField(help_text='Account ID from the platform', max_length=1000)),
                ('brokerage_authorization', models.CharField(help_text='Brokerage authorization ID', max_length=1000)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the account connection is active')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Attached Detail',
                'verbose_name_plural': 'Account Attached Details',
                'unique_together': {('user', 'platform_name', 'account_id')},
            },
        ),
    ]
