# Generated by Django 5.2.4 on 2025-08-07 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subscription plan', max_length=100)),
                ('duration', models.CharField(choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('12_months', '12 Months')], help_text='Duration of the subscription', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the subscription plan', max_digits=10)),
                ('credits', models.IntegerField(default=0, help_text='Number of credits included in this plan')),
                ('features', models.TextField(help_text='List of features included in this plan (one feature per line or comma separated)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for purchase')),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular plan for highlighting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['name', 'duration'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When the subscription expires', null=True)),
                ('credits_awarded', models.IntegerField(default=0, help_text='Credits awarded when this subscription was activated')),
                ('is_auto_renewal', models.BooleanField(default=False, help_text='Whether subscription auto-renews')),
                ('payment_reference', models.CharField(blank=True, help_text='Payment gateway reference/transaction ID', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='subscription.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
