# Generated by Django 5.2.4 on 2025-08-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='days',
            field=models.IntegerField(default=30, help_text='Number of days for this subscription plan'),
        ),
    ]
