# Generated by Django 5.2.4 on 2025-08-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionplan_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['name', 'duration'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-created_at'], 'verbose_name': 'User Subscription', 'verbose_name_plural': 'User Subscriptions'},
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.TextField(blank=True, help_text='List of features included in this plan (one feature per line or comma separated)', null=True),
        ),
    ]
