# Generated by Django 5.1.4 on 2025-02-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HindAi_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hindaiuser',
            options={},
        ),
    ]
