# Generated by Django 5.1.6 on 2025-04-04 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HindAi_users", "0002_alter_hindaiuser_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveInactiveUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minute", models.IntegerField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
