# Generated by Django 5.2.3 on 2025-08-19 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayPaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('entity', models.CharField(default='order', max_length=50)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('receipt', models.CharField(max_length=100)),
                ('status', models.CharField(default='created', max_length=50)),
                ('created_at', models.IntegerField()),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Razorpay Payment Gateway',
                'verbose_name_plural': 'Razorpay Payment Gateways',
                'db_table': 'razorpay_payment_gateway',
                'ordering': ['-created_timestamp'],
            },
        ),
    ]
